site_name: SwapDex Wiki
copyright: Copyright &copy; 2021 SwapDex
repo_url: https://github.com/Swapdex-Protocol/swapdex-documentation

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3
theme:
  palette:
    primary: pink
    scheme: default
    
  markdown_extensions:
  features:
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  custom_dir: overrides
  logo: assets/swapdex-logo-circlewhite.png
  favicon: assets/swapdex-icon.png
  language: en
google_analytics:
  - UA-190563951-2
  - auto
  
plugins:
  - search
  - i18n:
      languages:
        fr: "Français"
        en: "English"
      default_language: 'en'

extra:
  # Default mkdocs-material alternate links for untranslated pages
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
  alternate:
    - name: English
      link: ""
      lang: en

    - name: Français
      link: index.fr/
      lang: fr



 